### ISSUE TITLE
High-level rules throw an exception

### ISSUE THREAD

**Issue by ineu** [dryrb/dry-validation#61]
High-level rules described [here](https://github.com/dryrb/dry-validation/wiki/High-level-Rules) don't seem to work in the latest version (0.6.0 ATM). Copypaste of BarcodeSchema from that page throws following error:
```
[4] pry(main)> BarcodeSchema.new.call({})
NoMethodError: undefined method `input' for #<Dry::Logic::Rule::Conjunction:0x0055e497bb7c28>
from /home/ineu/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dry-logic-0.1.4/lib/dry/logic/rule/check.rb:8:in `evaluate_input'

```

**Comment by solnic** [comment]
This is going through a huge refactoring right now, including dry-logic refactor, it's very likely `rule` DSL won't be needed eventually.
